version: "3"

services:
  nano-node:
    image: nanocurrency/nano
    container_name: nano-node
    hostname: nano-node
    environment:
      - TERM=xterm
    restart: unless-stopped
    ports:
      - "7075:7075"
      - "::1:7076:7076"
      - "7078:7078"
    volumes:
      - /nano:/root

networks:
  default:
    external:
      name: nano-node-network
