const EXPIRE_1H = 3600;
const EXPIRE_24H = EXPIRE_1H * 24;
const EXPIRE_48H = EXPIRE_24H * 2;
const TOTAL_CONFIRMATIONS_COLLECTION = "TOTAL_CONFIRMATIONS";
const TOTAL_CONFIRMATIONS_KEY_24H = "TOTAL_CONFIRMATIONS_24H";
const TOTAL_CONFIRMATIONS_KEY_48H = "TOTAL_CONFIRMATIONS_48H";
const TOTAL_NANO_VOLUME_COLLECTION = "TOTAL_NANO_VOLUME";
const TOTAL_NANO_VOLUME_KEY_24H = "TOTAL_NANO_VOLUME_24H";
const TOTAL_NANO_VOLUME_KEY_48H = "TOTAL_NANO_VOLUME_48H";
const MARKET_CAP_RANK_COLLECTION = "MARKET_CAP_RANK_COLLECTION";
const MARKET_CAP_RANK = "MARKET_CAP_RANK";
const MARKET_CAP_RANK_24H = "MARKET_CAP_RANK_24H";
const COINGECKO_STATS = "COINGECKO_STATS";
const MONGO_URL = "mongodb://localhost:27017";
const MONGO_DB = "nanolooker";
const MONGO_OPTIONS = {
  useNewUrlParser: true,
  useUnifiedTopology: true
};

module.exports = {
  EXPIRE_1H,
  EXPIRE_24H,
  EXPIRE_48H,
  TOTAL_CONFIRMATIONS_COLLECTION,
  TOTAL_CONFIRMATIONS_KEY_24H,
  TOTAL_CONFIRMATIONS_KEY_48H,
  TOTAL_NANO_VOLUME_COLLECTION,
  TOTAL_NANO_VOLUME_KEY_24H,
  TOTAL_NANO_VOLUME_KEY_48H,
  MARKET_CAP_RANK_COLLECTION,
  MARKET_CAP_RANK,
  MARKET_CAP_RANK_24H,
  COINGECKO_STATS,
  MONGO_URL,
  MONGO_DB,
  MONGO_OPTIONS
};
