const EXPIRE_24H = 86400;
const EXPIRE_48H = EXPIRE_24H * 2;
const TOTAL_CONFIRMATIONS_COLLECTION = "TOTAL_CONFIRMATIONS";
const TOTAL_CONFIRMATIONS_KEY_24H = "TOTAL_CONFIRMATIONS_24H";
const TOTAL_CONFIRMATIONS_KEY_48H = "TOTAL_CONFIRMATIONS_48H";
const TOTAL_NANO_VOLUME_COLLECTION = "TOTAL_NANO_VOLUME";
const TOTAL_NANO_VOLUME_KEY_24H = "TOTAL_NANO_VOLUME_24H";
const TOTAL_NANO_VOLUME_KEY_48H = "TOTAL_NANO_VOLUME_48H";
const MONGO_URL = "mongodb://localhost:27017";
const MONGO_DB = "nanolooker";

module.exports = {
  EXPIRE_24H,
  EXPIRE_48H,
  TOTAL_CONFIRMATIONS_COLLECTION,
  TOTAL_CONFIRMATIONS_KEY_24H,
  TOTAL_CONFIRMATIONS_KEY_48H,
  TOTAL_NANO_VOLUME_COLLECTION,
  TOTAL_NANO_VOLUME_KEY_24H,
  TOTAL_NANO_VOLUME_KEY_48H,
  MONGO_URL,
  MONGO_DB
};
